### ISSUE TITLE
Ask for password if not in .deploy.yml file

### ISSUE THREAD

**Issue by tameroski** [bolt/simple-deploy#4]
I think it would be better not to store the password in the configuration file. Or at least ask for it if it's not present.

**Comment by GwendolenLynch** [comment]
Shouldn't be too hard to do, would you like to have a go at PRing something?

**Comment by tameroski** [comment]
Done with #5. Hope i did well 😓

**Comment by GwendolenLynch** [comment]
Legendary! :+1: 

It looks good on the first view, I'll have a bit of a better look later (today King's Day here in NL so a bit distracted :smile:)

**Comment by tameroski** [comment]
I'm not in a hurry. I'm finally switching to Capistrano because this package is a bit too light for my needs (releases management, git support, etc ...).
Happy King's Day btw 😄
